language: node_js
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: pages
  github-token: "$GH_TOKEN"
  on:
    branch: master
  local_dir: build
  edge: true
env:
  matrix:
    secure: s8GMaXTV7315Jppp+em54UUQNfjmvDbTiAoOAEbsC36dp5PFB6GJBDfAVR60Z1C6GAaygaHKJ3hNV945+tP7TQfjwVGZ0bN63JKnbeGt1VTxnEYs3LIgIdPGGQHFYhtQWMX936OHLj444mtE1twBhsqa3BQsYCQPRRWqvgJHViiJsgFArCzXaN/sKE+S9vSHvIH5ddEY+j60kT6EMynpoxggvM1RRJZ2C52mrn76drHYacZTKrVSVHQOzr/Ui1rf/eXv1c3Gw3dcxi9FuMs9RXQLP/S5PRti1fFB3QYXiVTGM/8c3UBjtwBPsBkFkf9/RyeGvtMFGNvqfp8653BVB9oXBEQB3wldoKndq7OXgu4IVSNcnyAmC6ffa2GbHichLIfDlXPH+1e/ymmXTqiHDaUvA+10Ixb+cdW+BM4z1uxSDFHHm1BCORKd0iGWZ0Ue2n55pkjlYQYfrJPJPuNKkxworVk1ucpXCSHQv01Jd8B7KJMc4qNBbnDauIq/uITeSth+Me9NHMX+fpmQzGNdF9fYGVz+qUzkbSEPSubJcWAf7vm9/snnNN/rzDjf9g2VTrW7TJzXCQN4IijkvkpZMWV7W4s4UIbJJAshJ/i7gJeSDECjBXgRWcsmhJgGTV4pIxIk4uY+qtu0V4AQLQZYObnCMwhUuWrUnvEVYwrW3Ds=
